# Generated by Django 4.1.7 on 2024-06-04 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endereco", models.CharField(blank=True, max_length=100, null=True)),
                ("cidade", models.CharField(blank=True, max_length=30, null=True)),
                ("bairro", models.CharField(blank=True, max_length=55, null=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Cliente",),
        migrations.DeleteModel(name="Produto",),
    ]
