# Generated by Django 4.1.7 on 2024-06-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dadosusuario_delete_cliente_delete_produto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imagem", models.ImageField(upload_to="produtos/")),
                ("quantidade", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
