# Generated by Django 4.1.7 on 2024-06-05 00:51

import datetime
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_itemcarrinho_carrinho"),
    ]

    operations = [
        migrations.RemoveField(model_name="produto", name="quantidade",),
        migrations.AddField(
            model_name="produto",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
        migrations.AddField(
            model_name="produto",
            name="criado",
            field=models.DateTimeField(
                default=datetime.datetime(1987, 7, 3, 0, 0),
                verbose_name="Data de Criação",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="estoque",
            field=models.PositiveIntegerField(default=0, verbose_name="Estoque"),
        ),
        migrations.AddField(
            model_name="produto",
            name="modificado",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Modificação"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(max_length=240, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                upload_to="produtos/",
                variations={},
                verbose_name="Imagem",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço"
            ),
        ),
    ]
