# Generated by Django 4.1.7 on 2024-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_produto_quantidade_produto_ativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("tradicional", "Tradicional"),
                    ("vegano", "Vegano"),
                    ("sem_glutem", "Sem Glúten"),
                ],
                default="Tradicional",
                max_length=20,
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="decoracao",
            field=models.CharField(
                choices=[("simples", "Simples"), ("elaborada", "Elaborada")],
                default="Simples",
                max_length=20,
                verbose_name="Decoração",
            ),
        ),
    ]
