# Generated by Django 4.1.7 on 2024-06-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_produto_criado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="estoque",
            field=models.PositiveIntegerField(default=500, verbose_name="Estoque"),
        ),
    ]
