# Generated by Django 4.1.7 on 2024-06-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_produto_cobertura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="cobertura",
            field=models.CharField(
                choices=[
                    ("creme_chocolate", "Creme de Chocolate"),
                    ("creme_morango", "Creme de Morango"),
                    ("creme_baunilha", "Creme de Baunilha"),
                    ("creme_maracuja", "Creme de Maracujá"),
                    ("raspa_coco", "Raspa de Coco"),
                    ("raspa_limao", "Raspa de Limão"),
                    ("buttercream", "Buttercream"),
                    ("chantilly.", "Chantilly"),
                    ("merengue", "Merengue"),
                    ("nozes", "Nozes"),
                ],
                default="Creme de Chocolate",
                max_length=20,
                verbose_name="Cobertura",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="sabor",
            field=models.CharField(
                choices=[
                    ("chocolate", "Chocolate"),
                    ("morango", "Morango"),
                    ("baunilha", "Baunilha"),
                    ("maracuja", "Maracujá"),
                    ("coco", "Coco"),
                    ("limao", "Limão"),
                    ("cenoura", "Cenoura"),
                ],
                default="Chocolate",
                max_length=20,
                verbose_name="Sabor",
            ),
        ),
    ]
