# Generated by Django 4.1.7 on 2024-06-06 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_produto_imagem"),
    ]

    operations = [
        migrations.RemoveField(model_name="carrinho", name="itens",),
        migrations.AddField(
            model_name="carrinho",
            name="criado",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de Criação"
            ),
        ),
        migrations.AddField(
            model_name="carrinho",
            name="modificado",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Modificação"
            ),
        ),
        migrations.AddField(
            model_name="itemcarrinho",
            name="carrinho",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="core.carrinho",
            ),
        ),
        migrations.AddField(
            model_name="itemcarrinho",
            name="cobertura",
            field=models.CharField(
                choices=[
                    ("creme_chocolate", "Creme de Chocolate"),
                    ("creme_morango", "Creme de Morango"),
                    ("creme_baunilha", "Creme de Baunilha"),
                    ("creme_maracuja", "Creme de Maracujá"),
                    ("raspa_coco", "Raspa de Coco"),
                    ("raspa_limao", "Raspa de Limão"),
                    ("buttercream", "Buttercream"),
                    ("chantilly.", "Chantilly"),
                    ("merengue", "Merengue"),
                    ("nozes", "Nozes"),
                ],
                default="creme_chocolate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemcarrinho",
            name="decoracao",
            field=models.CharField(
                choices=[("simples", "Simples"), ("elaborada", "Elaborada")],
                default="simples",
                max_length=20,
            ),
        ),
    ]
