# Generated by Django 4.1.7 on 2024-06-06 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_remove_carrinho_itens_carrinho_criado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "modificado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Modificação"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "decoracao",
                    models.CharField(
                        choices=[("simples", "Simples"), ("elaborada", "Elaborada")],
                        default="simples",
                        max_length=20,
                    ),
                ),
                (
                    "cobertura",
                    models.CharField(
                        choices=[
                            ("creme_chocolate", "Creme de Chocolate"),
                            ("creme_morango", "Creme de Morango"),
                            ("creme_baunilha", "Creme de Baunilha"),
                            ("creme_maracuja", "Creme de Maracujá"),
                            ("raspa_coco", "Raspa de Coco"),
                            ("raspa_limao", "Raspa de Limão"),
                            ("buttercream", "Buttercream"),
                            ("chantilly.", "Chantilly"),
                            ("merengue", "Merengue"),
                            ("nozes", "Nozes"),
                        ],
                        default="creme_chocolate",
                        max_length=20,
                    ),
                ),
                (
                    "preco_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Total"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="core.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.produto"
                    ),
                ),
            ],
        ),
    ]
